site_name: Cocoa Press Documentation
site_author: Cocoa Press, LLC.
site_description: >-
  Break Free from the Mold™
site_url: https://docs.cocoapress.com
repo_url: ""
use_directory_urls: true
nav:
  - 'Home': 'index.md'
  - 'Learn':
    - '3D Printing 101':
        - '101/index.md'
        - 'FFF And You': '101/FFF.md'
        - The Slicer: '101/Slicer.md'
        - Finding Models: '101/Models.md'
        - Layer Height: '101/Layers.md'
        - Motion Systems: '101/index.html#motion-systems'

    - 'Chocolate 101':
        - 'Types of Chocolate': 'Chocolate/Types.md'
        - 'Temperature & Temperament': 'Chocolate/Temperature.md' 
        - 'Food Safety': 'Chocolate/FoodSafety.md'
        - 'Ethics of Chocolate': 'Chocolate/Ethics.md'
      
  - 'Assembly':
    - 'Before You Start': 'Assembly/start.md'
    - 'Assembling Your Cocoa Press':
        - 'Assembly/index.md'
        - 'Hardware': 'Assembly/Hardware.md'
        - 'Extrusion Prep': 'Assembly/Extrusion.md'
        - 'Frame': 'Assembly/Frame.md'
        - 'Interior Panels': 'Assembly/IntPanels.md'
        - 'Z Axis': 'Assembly/ZAxis.md'
        - 'Bed': 'Assembly/Bed.md'
        - 'A/B Drives' : 'Assembly/ABDrives.md'
        - 'X/Y Gantry': 'Assembly/XYGantry.md'
        - 'A/B Idlers': 'Assembly/ABIdlers.md'
        - 'X/Y Joints': 'Assembly/XYJoints.md'
        - 'X Carriage': 'Assembly/XCarriage.md'
        - 'A/B Belt Path': 'Assembly/ABBelts.md'
        - 'Toolhead': 'Assembly/Toolhead.md'
        - 'Electronics': 'Assembly/Electronics.md'
        - 'Display': 'Assembly/Display.md'
        - 'Exterior Panels': 'Assembly/ExtPanels.md'
  
  - 'Getting Up and Running':
      - 'Quickstart': 'Printer/index.md'
      - 'Slicer Setup': 'Printer/SlicerSetup.md'
      - 'Loading Chocolate': 'Printer/Loading.md'
      - 'Printing': 'Printer/Printing.md'
      - 'Cleaning':
        - 'Cleaning Cartridges': 'Printer/Cleaning.md'
        - 'Cleaning Plungers': 'Printer/Plunger.md'
      - 'Storing Chocolate': 'Chocolate/FoodSafety.html#storing-chocolate'
      - 'Troubleshooting':
          - 'Common Issues': 'Troubleshooting/Common.md'

  - 'Advanced Chocolate Printing':
      - 'Advanced/index.md' 
      - 'What Can You Print?': 'Advanced/PrintableDesigns.md'
      - 'Designing Your Own Models': 'Advanced/DesignTips.md'
      - 'Advanced Slicer Use': 'Advanced/Slicer.md'
      - 'Making Large Prints': 'Advanced/LargePrints.md'
      - 'Updating Your Printer': 'Advanced/Flashing.md'
      - 'Troubleshooting': 'Advanced/Troubleshooting.md'

extra_css:
  - css/extra.css
  - "https://use.typekit.net/csv4mjm.css"
extra_javascript:
  - js/extra.js
theme:
  palette:
    primary: deep orange
  name: material
  favicon: img/favicon.svg  
  logo: img/logo/cocoa.png
  custom_dir: overrides/
  font:
    text:
      "museo-sans"
  features:
    - navigation.tracking #This will automatically produce a link at the top of the page with the current location for copying for people more trivially.
    - navigation.expand
    #- toc.autohide  #Automatically hides the header when the user scrolls past a certain point.
    #- navigation.indexes
    - navigation.path
    # - navigation.instant
    # - navigation.instant.prefetch
    - navigation.sections
    - toc.follow
    - search.share
    - search.suggest
    - navigation.prune #Automatically remove non-rendered HTML from the menu items, shrinking larger sites (and we're getting up there tbh.)
    - content.tooltips
    - content.tabs.link #Automatic linking of pages with the same type (ie DSP or GCode, etc.)
plugins:
    - search
    - include-markdown
    - exclude-search:
        exclude:
          - beta/*

    - minify:
        minify_html: true

    - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       width: 100%
       height: auto
       zoomable: true
       draggable: true
    - redirects:
        redirect_maps:
          'quickstart.md': 'Printer/index.md' #Must include original ending with .md even with use_directory_urls set to true.  
          'printedparts.md': 'https://thangs.com/designer/Cocoa%20Press/3d-model/Cocoa%20Press%203D%20Printed%20Parts-939895'

copyright: >
  Copyright &copy; <a href="https://cocoapress.com/">Cocoa Press, LLC</a>
  <div></div>
  <a href="#__consent">Cookie Settings</a>
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CocoaPress
      title: Cocoa Press Twitter
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/CocoaPress
      title: Cocoa Press Instagram
    - icon: fontawesome/brands/tiktok
      link: http://tiktok.com/@elianarose66
      title: Ellie's TikTok
    - icon: material/email-fast
      link: mailto:hello@cocoapress.com
      title: Support Email
    - icon: octicons/globe-16
      link: https://cocoapress.com/
      title: Cocoa Press Website
    - icon: fontawesome/brands/github
      link: https://github.com/CocoaPress/
      title: Cocoa Press GitHub Organization
  consent:
    title: Cookie Consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-1652R5G1WM
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! We'll be looking at this soon.

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true 
  - abbr
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - glossary/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - meta
  - admonition
  - toc:
      permalink: true
      title: Page Contents
