site_name: Cocoa Press Documentation
site_author: Cocoa Press, LLC.
site_description: >-
  Break Free from the Mold™
site_url: https://docs.cocoapress.com
repo_url: ""
use_directory_urls: false
nav:
  - 'Home': 'index.md'
  - 'Learn':
    - '3D Printing 101':
        - '101/index.md'
        - 'FFF And You': '101/FFF.md'
        - The Slicer: '101/Slicer.md'
        - Finding Models: '101/Models.md'
        - Layer Height: '101/Layers.md'
        - Motion Systems: '101/index.html#motion-systems'

    - 'Chocolate 101':
        - 'Types of Chocolate': 'Chocolate/Types.md'
        - 'Temperature & Temperament': 'Chocolate/Temperature.md' 
        - 'Food Safety': 'Chocolate/FoodSafety.md'
        - 'Ethics of Chocolate': 'Chocolate/Ethics.md'
      

  - 'Assembly':
    - 'Before You Start': 'Assembly/start.md'
    - 'Assembling Your Cocoa Press':
        - 'Assembly/index.md'
        - 'Hardware': 'Assembly/Hardware.md'
        - 'Extrusion Prep': 'Assembly/Extrusion.md'
        - 'Frame': 'Assembly/Frame.md'
        - 'A/B Drives' : 'Assembly/ABDrives.md'
        - 'A/B Idlers': 'Assembly/ABIdlers.md'
        - 'Z Axis': 'Assembly/ZAxis.md'
        - 'X Axis': 'Assembly/XAxis.md'
        - 'A/B Belts': 'Assembly/ABBelts.md'
        - 'Print Bed': 'Assembly/PrintBed.md'
        - 'Extruder': 'Assembly/Extruder.md'
        - 'Electronics & Wiring': 'Assembly/Electronics.md'
        - 'Skirt & Panels': 'Assembly/Skirt.md'
        - 'Tophat': 'Assembly/Tophat.md'
  
  - 'Getting Up and Running':
      - 'Quickstart': 'test/index.md'
      - 'Slicer Setup': 'Printer/SlicerSetup.md'
      - 'Loading Chocolate': 'Printer/Loading.md'
      - 'Cleaning Cartridges': 'Printer/Cleaning.md'
      - 'Updating Your Printer': 'Printer/Flashing.md'
      - 'Advanced Slicer Use': 'Printer/AdvancedSlicer.md'
      - 'Troubleshooting':
          - 'Troubleshooting/index.md'
          - 'Common Issues': 'Troubleshooting/Help.md'
          - 'Electronics': 'Troubleshooting/Electronics.md'
          - 'Slicer & Software': 'Troubleshooting/Slicer.md'
  
  #- 'Tags': tags.md
extra_css:
  - css/extra.css
  - "https://use.typekit.net/csv4mjm.css"
extra_javascript:
  - js/extra.js
theme:
  palette:
    primary: deep orange
  name: material
  favicon: img/favicon.svg  
  logo: img/logo/cocoa.png
  custom_dir: overrides/
  font:
    text:
      "museo-sans"
  features:
    - navigation.tracking #This will automatically produce a link at the top of the page with the current location for copying for people more trivially.
    - navigation.expand
    #- toc.autohide  #Automatically hides the header when the user scrolls past a certain point.
    #- navigation.indexes
    - navigation.path
    # - navigation.instant
    # - navigation.instant.prefetch
    - navigation.sections
    - toc.follow
    - search.share
    - search.suggest
    - navigation.prune #Automatically remove non-rendered HTML from the menu items, shrinking larger sites (and we're getting up there tbh.)
    - content.tooltips
    - content.tabs.link #Automatic linking of pages with the same type (ie DSP or GCode, etc.)
plugins:
    - search
    - include-markdown
    - exclude-search:
        exclude:
          - beta/*

    - minify:
        minify_html: true

    - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       width: 100%
       height: auto
       zoomable: true
       draggable: true

copyright: >
  Copyright &copy; <a href="https://cocoapress.com/">Cocoa Press, LLC</a>
  <div></div>
  <a href="#__consent">Cookie Settings</a>
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CocoaPress
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/CocoaPress
    - icon: fontawesome/brands/tiktok
      link: http://tiktok.com/@elianarose66
      title: "Support Forum"
    - icon: material/email-fast
      link: mailto:hello@cocoapress.com
    - icon: octicons/globe-16
      link: https://cocoapress.com/
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  analytics:
    provider: google
    property: G-1652R5G1WM
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! We'll be looking at this soon.

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 
  - abbr
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.snippets:
      auto_append:
        - glossary/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - md_in_html
  - meta
  - admonition
  - toc:
      permalink: true
      title: Page Contents
